### ISSUE TITLE
Python 2? Are you serious?

### ISSUE THREAD

**Issue by impredicative** [LittleWat/multichannel_semseg_with_uda#1]
Are you not aware that Python 2 is set to [expire soon](https://pythonclock.org/)? You should be using the latest Python 3.

**Comment by LittleWat** [comment]
Oops... Yeah, you are right. [2to3](https://docs.python.org/2/library/2to3.html) might be helpful but I have no time to reimplement. Sorry...orz

**Comment by impredicative** [comment]
You don't have time to run 2to3 and retest? That's really sad. Next time, please try using the current version of software if you want people to consider using it.
