### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (6) at non-singleton dimension 0

### ISSUE THREAD

**Issue by lly2111101** [LittleWat/multichannel_semseg_with_uda#2]
Hi, when I run command "python demo.py  sample_img/nyu/rgb_5947.png dual_model.tar", an error appeared which was "RuntimeError: The expanded size of the tensor (3) must match the existing size (6) at non-singleton dimension 0" in the transform module.

**Comment by lly2111101** [comment]
> Hi, when I run command "python demo.py sample_img/nyu/rgb_5947.png dual_model.tar", an error appeared which was "RuntimeError: The expanded size of the tensor (3) must match the existing size (6) at non-singleton dimension 0" in the transform module.

----------------------------------------


Solved~! thx

**Comment by LittleWat** [comment]
I am glad you could solve :)
